spring.datasource.url=jdbc:postgresql://localhost:54321/gymdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.kafka.bootstrap-servers=localhost:9092

hibernate.hbm2ddl.auto=validate
hibernate.show_sql=true

jwt.secret=52f8f8f95212e347b9cabedb65734e30962c6a627e773c75a63125c52a6c13a2
jwt.expire-time=604800000