spring.datasource.url=jdbc:postgresql://prod-host:5432/gymdb
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

hibernate.hbm2ddl.auto=validate
hibernate.show_sql=false

jwt.secret=${JWT_SECRET}
jwt.expire-time=${JWT_EXPIRATION_TIME}