spring.application.name=gym-service
server.port=8081

spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.validator.apply_to_ddl=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.profiles.active=dev

# *===========* microservice communication *===========* #
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.instance.preferIpAddress=true

resilience4j.circuitbreaker.instances.workloadService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.workloadService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.workloadService.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.workloadService.sliding-window-size=10
resilience4j.circuitbreaker.instances.workloadService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.workloadService.minimumNumberOfCalls: 5
resilience4j.circuitbreaker.instances.workloadService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.workloadService.automaticTransitionFromOpenToHalfOpenEnabled=true