DROP TABLE IF EXISTS training_types CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS trainee CASCADE;
DROP TABLE IF EXISTS trainer CASCADE;
DROP TABLE IF EXISTS trainee_trainer CASCADE;
DROP TABLE IF EXISTS training CASCADE;